apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-global-accelerator-controller.name" . }}-manager
  namespace: {{ include "aws-global-accelerator-controller.namespace" . }}
  labels:
    h3poteto.dev: aws-global-accelerator-controller
    role: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      h3poteto.dev: aws-global-accelerator-controller
      role: manager
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        h3poteto.dev: aws-global-accelerator-controller
        role: manager
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aws-global-accelerator-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - /aws-global-accelerator-controller
            - controller
            - --cluster-name={{ .Values.clusterName }}
            {{- if .Values.globalAcceleratorId }}
            - --existing-accelerator-arn={{ .Values.globalAcceleratorId | quote }}
            {{- end }}
            {{- if .Values.verbose }}
            - --v=4
            {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
