{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.serviceName }}
  namespace: {{ include "aws-global-accelerator-controller.namespace" . }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    h3poteto.dev: aws-global-accelerator-controller
    role: webhook
  type: ClusterIP
{{- end -}}
