{{- if .Values.webhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-global-accelerator-controller.name" . }}-webhook
  namespace: {{ include "aws-global-accelerator-controller.namespace" . }}
  labels:
    h3poteto.dev: aws-global-accelerator-controller
    role: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      h3poteto.dev: aws-global-accelerator-controller
      role: webhook
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        h3poteto.dev: aws-global-accelerator-controller
        role: webhook
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aws-global-accelerator-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: webhook-tls
          secret:
            secretName: {{ .Values.webhook.certificateSecretName }}
      containers:
        - name: webhook
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - /aws-global-accelerator-controller
            - webhook
            - --tls-cert-file=/etc/webhook/certs/tls.crt
            - --tls-private-key-file=/etc/webhook/certs/tls.key
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/webhook/certs
              name: webhook-tls
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
