name: Build

on:
  push:
    branches:
      - master

  pull_request:

env:
  KIND_VERSION: v0.27.0
  KUBECTL_VERSION: v1.32.4
  HELM_VERSION: v3.17.3
  HELMFILE_VERSION: v0.171.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: ${{ env.KIND_VERSION }}
      - name: Install kubectl
        env:
          KUBECTL_VERSION: ${{ env.KUBECTL_VERSION }}
          BIN_DIR: ${{ github.workspace }}/tools
        run: |
          mkdir -p $BIN_DIR
          curl -sSLo "$BIN_DIR/kubectl" "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          chmod +x "$BIN_DIR/kubectl"
          echo "$BIN_DIR" >> "$GITHUB_PATH"
      - name: Install helm
        env:
          HELM_VERSION: ${{ env.HELM_VERSION }}
          BIN_DIR: ${{ github.workspace }}/tools
        run: |
          mkdir -p $BIN_DIR
          curl -sSLo "$BIN_DIR/helm-${HELM_VERSION}-linux-amd64.tar.gz" "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz"
          tar -xvf "$BIN_DIR/helm-${HELM_VERSION}-linux-amd64.tar.gz"
          mv "linux-amd64/helm" "$BIN_DIR/helm"
          chmod +x "$BIN_DIR/helm"
          echo "$BIN_DIR" >> "$GITHUB_PATH"
      - name: Install helmfile
        env:
          HELMFILE_VERSION: ${{ env.HELMFILE_VERSION }}
          BIN_DIR: ${{ github.workspace }}/tools
        run: |
          mkdir -p $BIN_DIR
          curl -sSLo "$BIN_DIR/helmfile" "https://github.com/roboll/helmfile/releases/download/${HELMFILE_VERSION}/helmfile_linux_amd64"
          chmod +x "$BIN_DIR/helmfile"
          echo "$BIN_DIR" >> "$GITHUB_PATH"
      - name: Run node-manager
        run: |
          helm template --debug node-manager -n kube-system ./stable/node-manager
      - name: Install node-manager
        working-directory: ./examples/node-manager
        run: |
          helmfile sync
      - name: Run fluentd-sidecar-injector
        run: |
          helm template --debug fluentd-sidecar-injector -n kube-system ./stable/fluentd-sidecar-injector
      - name: Run kms-secrets
        run: |
          helm template --debug kms-secrets -n kube-system ./stable/kms-secrets
      - name: Run eks-pod-identity-webhook-installer
        run: |
          helm template --debug eks-pod-identity-webhook-installer -n kube-system ./stable/eks-pod-identity-webhook-installer
      - name: Run aws-global-accelerator-controller
        run: |
          helm template --debug global-accelerator-controller -n kube-system ./stable/aws-global-accelerator-controller
